### ISSUE TITLE
Wrong link redirection

### ISSUE THREAD

**Issue by Cocazou** [Hypno123/theisle-bugs#4]
Patch: 5575
Server: /
Description: If you click on the patch version (look at screenshot) it redirects to the store news instead of the game news/patch notes

Screenshot : 
![patch link](https://user-images.githubusercontent.com/35146192/35750147-549c4240-0854-11e8-96eb-efbb2abfbeb7.PNG)

**Comment by Hypno123** [comment]
Will send you to the announcements rather than store page next update.
